### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by ilovefreesw** [parzuko/followedby#1]
Can't seem to be working in Chrome as well as Edge

**Comment by parzuko** [comment]
Hey, thanks for creating this issue! Have you installed the extension via the [chrome store](https://www.getfollowedby.xyz/download/chrome)?
Also, just want to clear up a bit of the functionality (incase that was confusing):
- the extension goes through the profile you're `visiting's followers` and `your following`. The rendered UI is for the overlap between the two lists. 
- currently there is no state for when there is no overlap -> that may be the problem you're facing

Let me know if this helped or if I can help you in some other way?

**Comment by ilovefreesw** [comment]
Tried from the repo as well as Chrom web store. Neither works. These are 3 profiles I am trying

@shobhit-ilfs @ilovefreesw  @suleman-elahi

![image](https://user-images.githubusercontent.com/77317006/182369652-fe04d8eb-09b8-40af-97e7-a22634c3117a.png)

**Comment by parzuko** [comment]
That's odd. Looking into this; will get back to you on this ASAP
In the meantime, could you share logs from the `Network` and `Console` tab when the page first renders?

**Comment by ilovefreesw** [comment]
Seems requests are being blocked. I will try after using a VPN.

![image](https://user-images.githubusercontent.com/77317006/182371517-78fd860d-1ff2-4c0c-bad5-110f7ad8f555.png)

![image](https://user-images.githubusercontent.com/77317006/182371548-531854ac-5cd4-4234-8e02-d956838f9865.png)

**Comment by parzuko** [comment]
Can you also share the `response` to the 403 fetch call?

**Comment by parzuko** [comment]
If you are using the GitHub public API for a personal project of your own, it could be that you have been rate limited from accessing the results. Doesn't seem to be a problem with the profiles -> here's how it looks if i visit these profiles (after following you)

https://user-images.githubusercontent.com/57803819/182372362-1c39a64a-cdbf-44ea-99dc-2110804d05bb.mov



https://user-images.githubusercontent.com/57803819/182372296-6334e367-f49e-465d-a4d4-968ec04fdd3f.mov

**Comment by ilovefreesw** [comment]
Yeah 400 error explains that. That's why I said I will try after using a VPN

**Comment by ilovefreesw** [comment]
It works after using VPN. It appears my IP is black listed.
